### ISSUE TITLE
Describe relationship to ceedubs/sbt-ctags

### ISSUE THREAD

**Issue by raboof** [kalmanb/sbt-ctags#11]
It is unclear to me how this sbt-ctags relates to https://github.com/ceedubs/sbt-ctags

**Comment by kalmanb** [comment]
They preform very similar tasks. The only difference that I can see is that kalmanb/sbt-ctags allows you to 'add' and tag the libraries that you select. It looks to me that ceedubs/sbt-ctags add all the libraries. At work we have a few big projects and we don't want all sources imported, just the ones we are currently using, so you can add and remove libs as you please, or just add all (ctagsAdd *) if you want them all.
