### ISSUE TITLE
ctags: No files specified.

### ISSUE THREAD

**Issue by jimenezrick** [kalmanb/sbt-ctags#9]
Running in the SBT console:

```
> ctagsDownload
> ctagsAdd *
```

I get:

```
...
Added source for ...
Added source for ...
ctags: No files specified. Try "ctags --help".
```

I'm having a look at the plugin's code but  I cannot see what is happening. Any idea?

**Comment by kalmanb** [comment]
The last line is running the ctags command and failing. Try running ctags manually in your shell. 

Once you have ctags working correctly in your shell, you may need to use a custom command. To run a custom command see https://github.com/kalmanb/sbt-ctags/blob/master/conf/CustomCtagsPlugin.scala

**Comment by jimenezrick** [comment]
Running `ctags -R` manually, it works fine.

This is my output inside sbt:

```
Added source for com.typesafe:scalalogging-slf4j_2.10:1.1.0:test
Added source for com.google.protobuf:protobuf-java:2.5.0:test
Added source for org.apache.zookeeper:zookeeper:3.3.4:test
Added source for com.yammer.metrics:metrics-core:2.2.0:test
Added source for net.sandrogrzicic:scalabuff-runtime_2.10:1.3.7:test
Added source for org.apache.kafka:kafka_2.10:0.8.1.1:test
Added source for junit:junit:3.8.1:test
Added source for io.argonaut:argonaut_2.10:6.0.4:test
Added source for com.101tec:zkclient:0.3:test
Added source for org.slf4j:slf4j-api:1.7.5:test
Added source for jline:jline:0.9.94:test
Added source for org.xerial.snappy:snappy-java:1.0.5:test
Added source for com.typesafe:config:1.2.1:test
Added source for org.scalaz:scalaz-core_2.10:7.0.6:test
Added source for org.scala-lang:scala-reflect:2.10.3:test ()
Added source for org.scala-lang:scala-library:2.10.4:test ()
Added source for org.twitter4j:twitter4j-stream:4.0.2:test
Added source for org.twitter4j:twitter4j-core:4.0.2:test
Added source for net.sf.jopt-simple:jopt-simple:3.2:test
Added source for com.hazelcast:hazelcast-client:3.1.6:test
Added source for org.scalaj:scalaj-collection_2.10:1.5:test
Added source for com.hazelcast:hazelcast:3.1.6:test
ctags: No files specified. Try "ctags --help".
```

Is that `()` normal? Why my dependencies appear as **test** when they are used for the **compile** tasks?

Thanks!

**Comment by kalmanb** [comment]
Yes the () is normal for scala libs. They present slightly differently than standard libs.
The test scope, I think it's because I load the test scope so that you can include test libs too. It probably means that all libs are presented as "test" and not compile. It won't effect behaviour though. 

All the plugin essentially does is unzips the selected sources from your ivy cache into your local project so that ctags can index them for you.

Enjoy

**Comment by jimenezrick** [comment]
One last thing, could be possible that this line is wrong?
`"ctags" !` - https://github.com/kalmanb/sbt-ctags/blob/master/src/main/scala/com/kalmanb/sbt/CtagsPlugin.scala#L161

_ctags_ should be run as `ctags -R` given that no source files are passed as arguments when invoked. Maybe there are versions of ctags that work well, but `-R` is necessary.

Thanks!
